import "./globals.css";

import React from "react";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { SWRProvider } from "@/app/swr-provider";
import FooterLogo from "@/components/pages/footerLogo";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-linear font-sans antialiased",
          fontSans.variable,
        )}
      >
        <SWRProvider>
          <div className={"min-h-[calc(100vh-33px)]"}>{children}</div>
          <FooterLogo />
        </SWRProvider>
      </body>
    </html>
  );
}
