import "./globals.css";

import React from "react";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { SWRProvider } from "@/app/swr-provider";
import FooterLogo from "@/components/pages/FooterLogo";

import localFont from "next/font/local";

const acronymFont = localFont({
  src: [
    {
      path: "../assets/fonts/acronym_regular.woff2",
      weight: "400",
    },
    {
      path: "../assets/fonts/acronym_semibold.woff2",
      weight: "600",
    },
  ],
  variable: "--font-acronym",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col bg-linear font-sans antialiased",
          acronymFont.variable,
        )}
      >
        <SWRProvider>
          <main className={"h-1 flex-1"}>{children}</main>
          <FooterLogo />
        </SWRProvider>
      </body>
    </html>
  );
}
